### ISSUE TITLE
problem with VegaLite in jupyter lab

### ISSUE THREAD

**Issue by Jianqing001** [queryverse/VegaLite.jl#356]
using VegaLite, DataFrames
df = DataFrame(category=1:6, value=[4,6,10,3,7,8])
df |> @vlplot(mark={:arc, innerRadius=50}, theta=:value, color="category:n", view={stroke=nothing})
#jupyterlab==3.0

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '../../deps/node_modules/vega-lite'
Require stack:
- D:\julia\data\packages\VegaLite\CzoMX\src\rendering\vl2vg.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\julia\data\packages\VegaLite\CzoMX\src\rendering\vl2vg.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\julia\\data\\packages\\VegaLite\\CzoMX\\src\\rendering\\vl2vg.js'
  ]
}
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'D:\julia\data\packages\VegaLite\CzoMX\deps\node_modules\vega-cli\bin\vg2svg'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Javascript Error: Cannot read property 'orient' of undefined
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '../../deps/node_modules/vega-lite'
Require stack:
- D:\julia\data\packages\VegaLite\CzoMX\src\rendering\vl2vg.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\julia\data\packages\VegaLite\CzoMX\src\rendering\vl2vg.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\julia\\data\\packages\\VegaLite\\CzoMX\\src\\rendering\\vl2vg.js'
  ]
}
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'D:\julia\data\packages\VegaLite\CzoMX\deps\node_modules\vega-cli\bin\vg2png'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by davidanthoff** [comment]
This looks to me as if you are on a very old version of VegaLite.jl. What version of the package are you using at the moment?

**Comment by Jianqing001** [comment]
VegaLite v 1.0.0
julia        V 1.5.3
jupyterlab  V3.0

**Comment by Jianqing001** [comment]
> 在我看来，这好像是在使用VegaLite.jl的非常旧的版本。您目前正在使用哪个版本的软件包？

VegaLite  v 1.0.0
julia         v1.5.3
jupyterlab v3.0

**Comment by davidanthoff** [comment]
Your version of VegaLite.jl is way outdated, we are currently at version 2.3.1. Older versions had some issues around deployment, but those should all be fixed in recent versions.

**Comment by Jianqing001** [comment]
Thank you very much
